b2b_festival/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from b2b_festival import settings

# urlpatterns = [
#     path("", include('main.urls')),
#     path('admin/', admin.site.urls),
#     path("dda_blog/", include('dda_blog.urls')),
# ]
urlpatterns = [
    path("", include('dance_school.urls')),
    path('admin/', admin.site.urls),
    path("b2b/", include('main.urls')),
    path("blog/", include('dda_blog.urls')),
    path("privacy/", include('privacy.urls')),
    path(r'^tinymce/', include('tinymce.urls')),
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dance_school/urls.py
from django.urls import path
from . import views

app_name = 'dance_School'  # here for namespacing of urls.

urlpatterns = [
    path("", views.dance_school, name="dance_school"),
    path("schoolMessage", views.send_school_site_message, name="schoolMessage"),

]

dda_blog/urls.py
from django.urls import path
from . import views

app_name = 'dda_blog'  # here for namespacing of urls.

urlpatterns = [
    path("", views.blog_main_mage, name='dekadance_blog'),
    path('<slug:slug>/', views.blog_details_page, name='post_detail'),

]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("ticketing/", views.ticketing, name="ticketing"),
    path("past_editions/", views.past_edition, name="past_editions"),
    path("buyTickets", views.buyTicket, name="buyTickets"),
    path("festivalMessage", views.send_festival_site_message, name="festivalMessage"),
]

privacy/urls.py
from django.urls import path
from . import views


app_name = 'privacy'  # here for namespacing of urls.

urlpatterns = [
    path("", views.privacy, name="privacy")
]

dda_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Category(models.Model):
    CATEGORIES = (
        ('NEWS', 'School News'),
        ('DANCE_TIPS', 'Dance Tips'),
        ('OPINIONS', 'Opinions')
    )

    category = models.CharField(max_length=20, choices=CATEGORIES)

    def __int__(self):
        print(self.category)
        return self.category

    def __str__(self):
        return str(self.category)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = HTMLField()
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    imageURL = models.TextField()

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def return_full_name(self):
        return self.author.get_full_name()

dda_blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views.decorators.cache import cache_control
from django.views.decorators.vary import vary_on_headers

from .models import Post


# @cache_control(private=True, max_age=3600)
# @vary_on_headers('User-Agent')
def blog_main_mage(request):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    filtered_post_list = Post.objects.filter(status=1, category=1).order_by('-created_on')

    paginator = Paginator(queryset, 10) # Show 10 Posts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request=request,
                  template_name='dda_blog/dda_blog.html',
                  context={"filtered_post_list": filtered_post_list, 'page_obj': page_obj
                           })


# @cache_control(private=True, max_age=3600)
# @vary_on_headers('User-Agent')
def blog_details_page(request, slug):
    post_list = Post.objects.filter(status=1).order_by('-created_on')
    post = Post.objects.get(slug=slug)
    # post = Post.objects.all()[0]
    return render(request=request,
                  template_name='dda_blog/dda_blog_detail.html',
                  context={"post": post,
                           "post_list": post_list
                           })

dda_blog/templates/dda_blog/dda_blog.html
{% extends "dda_blog/dda_blog_base.html" %}

{% block content %}
    <!--================ Start Blog Post Area =================-->
    <section class="blog-post-area section-margin mt-4">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    {% for post in page_obj %}
                        <div class="single-recent-blog-post">
                            <div class="thumb">
                                <img class="img-responsive" src={{ post.imageURL }} alt="">
                                <ul class="thumb-info">
                                    <li><i class="ti-user"></i>{{ post.author }}</li>
                                    <li><i class="ti-notepad"></i>{{ post.created_on }}</li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="{% url 'dda_blog:post_detail' post.slug %}">
                                    <h2 class="blog-title">{{ post.title }}</h2>
                                </a>
                                <p class="tag-list-inline">Tag: {{ post.category }}</p>
                                <p class="tiny_class">{{ post.content|slice:":1200" | safe }}</p>
                                <a class="button" href="{% url 'dda_blog:post_detail' post.slug %}">Read More <i
                                        class="ti-arrow-right"></i></a>
                            </div>
                            <hr>
                        </div>
                    {% endfor %}
                    <div class="row">
                        <div class="col-lg-12">
                            <nav class="blog-pagination justify-content-center d-flex">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}" class="page-link"
                                               aria-label="Previous">
                                          <span aria-hidden="true">
                                              <i class="ti-angle-left"></i>
                                          </span>
                                            </a>
                                        </li>
                                    {% endif %}

                                    <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a>
                                    </li>


                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link"
                                               aria-label="Next">
                                          <span aria-hidden="true">
                                              <i class="ti-angle-right"></i>
                                          </span>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <!-- Start Blog Post Siddebar -->
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        {#                        <div class="single-sidebar-widget newsletter-widget">#}
                        {#                            <h4 class="single-sidebar-widget__title">Newsletter</h4>#}
                        {#                            <div class="form-group mt-30">#}
                        {#                                <div class="col-autos">#}
                        {#                                    <input type="text" class="form-control" id="inlineFormInputGroup"#}
                        {#                                           placeholder="Enter email" onfocus="this.placeholder = ''"#}
                        {#                                           onblur="this.placeholder = 'Enter email'">#}
                        {#                                </div>#}
                        {#                            </div>#}
                        {#                            <button class="bbtns d-block mt-20 w-100">Subcribe</button>#}
                        {#                        </div>#}

                        <div class="single-sidebar-widget popular-post-widget">
                            <h4 class="single-sidebar-widget__title">Latest News</h4>
                            <div class="popular-post-list">
                                {% for post in filtered_post_list %}
                                    <div class="single-post-list">
                                        <div class="thumb">
                                            <img class="img-thumbnail rounded-0" src={{ post.imageURL }} alt="">
                                            <ul class="thumb-info">
                                                <li>{{ post.author }}</li>
                                                <li>{{ post.created_on | date:"M d, Y" }}</li>
                                            </ul>
                                        </div>
                                        <div class="details mt-20">
                                            <a href="{% url 'dda_blog:post_detail' post.slug %}">
                                                <h3>{{ post.title }}</h3>
                                            </a>
                                        </div>
                                    </div>
                                    <hr>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        <!-- End Blog Post Siddebar -->
        </div>
    </section>
    <!--================ End Blog Post Area =================-->

{% endblock %}

dda_blog/templates/dda_blog/dda_blog_base.html
<!DOCTYPE html>
{% load tinymce_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DekaDance Academy - Blog</title>
    {% load static %}
    <link rel="icon" href="../../static/dda_blog/assets/img/logo/logo2.png" type="image/png">
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({selector: 'textarea', mode: "textareas", theme: "advanced"});</script>
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link type="text/css" href={% static '/dda_blog/assets/linericon/style.css' %} rel="stylesheet"/>
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link type="text/css" href={% static '/dda_blog/assets/css/style.css' %} rel="stylesheet"/>
</head>
<body>
<!--================Header Menu Area =================-->
<nav class="navbar navbar-dark navbar-fixed-top blog-navbar">
    <div class="container-fluid">
        <div class="nav-header">
            <a href="{% url 'dance_School:dance_school' %}">
                <div class="logo-dda"></div>
            </a>
        </div>
    </div>
</nav>
<!--================Header Menu Area =================-->

<main class="site-main">
    <!--================Hero Banner start =================-->
    <section class="mb-30px">
        <div class="container">
            <div class="hero-banner">
                <div class="hero-banner__content">
                    <h1>Deka Dance Academy</h1>
                    <h2>a BLOG about</h2>
                    <h3>School news</h3>
                    <h3>Dance Opinions</h3>
                </div>
            </div>
        </div>
    </section>
    <!--================Hero Banner end =================-->

    {% block content %}
        <!-- Content Goes here -->
    {% endblock content %}

    <!--================ Start Footer Area =================-->
    <footer class="footer-area section-padding">
        <div class="container">

            <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
                <p class="footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by
                    <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    <p><a href="{% url 'privacy:privacy' %}">Privacy Notice</a></p>
            </div>
        </div>
    </footer>
    <!--================ End Footer Area =================-->
</main>
<script src="../../static/dda_blog/assets/js/main.js" type=""></script>
</body>
</html>

dda_blog/templates/dda_blog/dda_blog_detail.html
{% extends "dda_blog/dda_blog_base.html" %}

{% block content %}


    <!--================ Start Blog Post Area =================-->
    <section class="blog-post-area section-margin">
        <div class="container">

            <div class="row">
                <div class="col-lg-8">
                    <div class="main_blog_details">
                        <img class="img-responsive" src={{ post.imageURL }} alt="">
                        <h2 class="blog-title">{{ post.title }}</h2>
                        <br>
                        <a class="button" href="{% url 'dda_blog:dekadance_blog' %}">BACK <i
                                class="ti-arrow-left"></i></a>
                        <div class="user_details">
                            <div class="float-right mt-sm-0 mt-3">
                                <div class="media">
                                    <div class="media-body">
                                        <h5>{{ post.author }}</h5>
                                        <p>{{ post.created_on | date:"M d, Y" }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            {{ post.content | safe }}
                        </div>
                    </div>
                    <a class="button" href="{% url 'dda_blog:dekadance_blog' %}">BACK <i
                            class="ti-arrow-left"></i></a>
                </div>
                <!-- Start Blog Post Siddebar -->
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        <div class="single-sidebar-widget popular-post-widget">
                            <h4 class="single-sidebar-widget__title">Latest Blog Posts</h4>
                            <div class="popular-post-list">
                                {% for post in post_list %}
                                    <div class="single-post-list">
                                        <div class="thumb">
                                            <img class="img-thumbnail rounded-0" src={{ post.imageURL }} alt="">
                                            <ul class="thumb-info">
                                                <li>{{ post.author }}</li>
                                                <li>{{ post.created_on | date:"M d, Y" }}</li>
                                            </ul>
                                        </div>
                                        <div class="details mt-20">
                                            <a href="{% url 'dda_blog:post_detail' post.slug %}">
                                                <h3>{{ post.title }}</h3>
                                            </a>
                                        </div>
                                    </div>
                                    <hr>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Blog Post Siddebar -->
        </div>
    </section>
    <!--================ End Blog Post Area =================-->
{% endblock %}